### PR TITLE
shadows into mainmenu

### PR DESCRIPTION
**Pull request by jardafis**
mainmenu with shadows, if you like.

### CODE REVIEW

**Comment by iratahack** [comment]
@jardafis , main menu looks good. I'll need to see how it fits with the redefine keys screen. They are the same image with the menu options removed.

What do you think about adding a lightning strike? I can toggle the ink color to make it flicker in the game.

**Comment by jardafis** [comment]
@iratahack , sounds good. You can try it and we will see what is better.

**Comment by iratahack** [comment]
@jardafis , what color border do you suggest? Dark blue?

**Comment by jardafis** [comment]
@iratahack , dark blue will fine.

**Pull request merged**
